version: "3.8"

services:
  shop-ui:
    build:
      context: ./shop-ui
      dockerfile: Dockerfile

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
